### PR TITLE
poi_marker: Set poi manager init pose to match robot initial pose

### PR DESCRIPTION
**Pull request by jamendezib**
After setting the initial pose, the poi manager stays still in the place where the initial pose was selected instead of moving to the origin.

### CODE REVIEW

**Comment by jamendezib** [comment]
@RomanRobotnik @alex-arnal

**Review by RomanRobotnik — APPROVED** [review]
Looks great!

Thx

**Comment by RomanRobotnik** [comment]
@jamendezib Can you increase the package version of poi_marker package?

**Comment by jamendezib** [comment]
> @jamendezib Can you increase the package version of poi_marker package?

Done @RomanRobotnik

**Pull request merged**
